//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otopark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int RelationshipID { get; set; }
        public int VehicleID { get; set; }
        public int CustomerID { get; set; }
        public int PersonelID { get; set; }
        public int PlaceID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Place Place { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
